version: '3.9'

services:
  app:
    build: .
    ports:
      - "5001:5000"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - .:/app
    environment:
      FLASK_APP: todo_project/run.py
      FLASK_ENV: development
    command: python todo_project/run.py

  owasp-zap:
    image: owasp/zap2docker-stable
    ports:
      - "8091:8090"
    command: zap.sh -daemon -port 8090
